### ISSUE TITLE
Installation with Jupyter Notebooks

### ISSUE THREAD

**Issue by dmccreary** [takluyver/mobilechelonian#18]
Hi.  Thank you for your code.  Can you tell me how to install it on a Jupyter Notebook?
Thanks!

**Comment by dmccreary** [comment]
I got this to work:

$ pip install mobilechelonian

**Comment by takluyver** [comment]
Thanks, I added a note to the README.

**Comment by dmccreary** [comment]
Huge thanks for your work.  I am using this for doing online training in our Minnesota CoderDojo courses that are moving online.  Cheers!

**Comment by takluyver** [comment]
Thanks, I'm glad it's still useful even though I've given it basically no attention for years.
