### ISSUE TITLE
Working with Screen objects

### ISSUE THREAD

**Issue by rlvaugh** [takluyver/mobilechelonian#19]
In standard turtle, you can setup a turtle screen so that you can control its size and position:

Normally, I would do this as:

from turtle import Turtle, Screen
screen = Screen()
screen.setup(width=600, height=600, startx=600, starty=300)

Is there a way to do something similar in mobilechelonian? I need to set the screen width & height in the notebook output cell.

**Comment by takluyver** [comment]
Sorry, it draws on a fixed 400 x 400 area at the moment. The code for mobilechelonian is all pretty basic. I don't think it would be hard to allow a custom screen size (probably on the `Turtle` object itself, rather than a separate Screen class), but I'm unlikely to get to it myself.

**Comment by rlvaugh** [comment]
Okay. Thanks for your quick reply! 400 x 400 may be large enough for my needs.
