### ISSUE TITLE
New version for this extension

### ISSUE THREAD

**Issue by kandjiabdou** [takluyver/mobilechelonian#22]
Hi guys,

I forked your repository for the purpose of an internship to correct some errors and personalize it for teaching at the IUT de villetaneuse.
So I created a new extension from yours ([here is the link](https://github.com/kandjiabdou/turtleiutv)). That extension was made as part of a 3-month internship at the iut of villetaneuse under the supervision of M. Lacroix.
I did a complete rewrite of some files and organized in a clean way.

Test it on binder
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/kandjiabdou/turtleiutv/master?filepath=Test.ipynb)

So I observed a strange effect when the turtle near the edge of the drawing area and bugs on the turtle speed display, sometimes the lines are not drawn and other issues.

Here are some bugs fixed
```python
# This code does not draw a perfect square due to limitations
from mobilechelonian import Turtle
t = Turtle()
t.speed(5)
for i in range(4):
    t.right(90)
    t.forward(300)
```
![image1](https://raw.githubusercontent.com/kandjiabdou/blog/master/code.png)
```python
# This code does not draw the line
# because the speed is greater than the added variation
t = Turtle()
t.speed(5)
for i in range(10):
    t.forward(5)
t.penup()
t.forward(100)
```
![image2](https://raw.githubusercontent.com/kandjiabdou/blog/master/code2.png)

Greetings
Abdou KANDJI

**Comment by takluyver** [comment]
Thanks! Do you think it's practical to try merging your changes into this repository, or do you prefer to maintain it separately?

**Comment by kandjiabdou** [comment]
> 

> Thanks! Do you think it's practical to try merging your changes into this repository, or do you prefer to maintain it separately?

Yes if you wish we can merge it, no problem.
