### ISSUE TITLE
Version number does not match with the latest tag

### ISSUE THREAD

**Issue by lsoksane** [takluyver/mobilechelonian#24]
`__version__` in `__init__` is 0.4 while git tag is 0.5.

**Comment by takluyver** [comment]
Yup, sorry about that. If it matters to you, we'd need to make a 0.6 release with that corrected.

**Comment by lsoksane** [comment]
This is not too important. I just noticed this as I tried to create an environment.yml file with the version numbers reported by packages themselves.
