### ISSUE TITLE
t.backward() going down instead of moving back

### ISSUE THREAD

**Issue by vlabbe7** [takluyver/mobilechelonian#7]
I think there is a bug in the code of the method backward(). The turtle goes down, instead of moving back.
```python
from mobilechelonian import Turtle
t = Turtle()
t.speed(5)

t.forward(100)
t.backward(100) 
```

![image](https://user-images.githubusercontent.com/29369917/27029587-3c1b5a52-4f69-11e7-8929-0b9de54e4415.png)

**Comment by takluyver** [comment]
Weird. It looks like the code uses the same maths as `forward()`, but with the signs switched. Can you see the mistake?

**Comment by vlabbe7** [comment]
I agree with you : it's weird.
Il have looked into the code. I have not found the bug.

Another test
```python
t.forward(100)
t.left(90)
t.backward(50)
```
That should give
![image](https://user-images.githubusercontent.com/29369917/27040377-14513b36-4f91-11e7-8fa8-6575274eb9b7.png)

Bug it gives
![image](https://user-images.githubusercontent.com/29369917/27040460-55e2ee46-4f91-11e7-8ade-6201c07e5787.png)

**Comment by vlabbe7** [comment]
I think there's a problem of a quarter of turn.

I can't find the problem in the code because i don't understand what ``self.bearing`` means exactly, for example what means

- ``self.bearing`` equals 0
- ``self.bearing`` equals 90
- ``self.bearing`` equals -90 ?

 (There is a lack of information about that).

I have seen the merge request #5 with a change between cos and sin.

There is at ``self.bearing = 90`` at https://github.com/takluyver/mobilechelonian/blob/master/mobilechelonian/__init__.py#L38

**Comment by takluyver** [comment]
Bearing is like compass bearing: 0 means north (or upwards), 90 is east (right), and so on. `self.bearing = 90` tells it to start pointing right.

Maybe it was fixed in #5 but the fix isn't released yet.

**Comment by takluyver** [comment]
I think #5 may well have fixed it - I've just made a 0.4 release, can you install it and have a go?

**Comment by vlabbe7** [comment]
I upgraded to 0.4 release.
# test 1 : ok
```python
from mobilechelonian import Turtle
t = Turtle()
t.speed(5)

t.forward(100)
t.backward(100)
```
![image](https://user-images.githubusercontent.com/29369917/27049500-d7bb8d56-4faf-11e7-9e6f-5956815d5038.png)

# test 2 :  ok
```python
from mobilechelonian import Turtle
t = Turtle()
t.speed(5)

t.forward(100)
t.left(90)
t.backward(50)
```
![image](https://user-images.githubusercontent.com/29369917/27049646-35e92014-4fb0-11e7-8b6f-9fbb05e183d8.png)

# Conclusion
I think the bug is fixed ! Thanks !

**Comment by takluyver** [comment]
Hooray! Thanks to @FranciscoMoya who fixed it :-)
